# vim: set ft=yaml fenc=utf-8 ff=unix sw=2 ts=2 et :
version: "3"

vars:
  APP_NAME: winfocus
  VERSION:
    sh: git describe --tags --always --dirty | sed 's/^v//'
  ARCH: x64

tasks:
  default:
    desc: クリーンビルドを実行する
    cmds:
      - task: clean
      - task: build

  clean:
    desc: out/ 以下のファイルを削除
    cmds:
      - cmd: pwsh.exe -NoProfile -Command "if (Test-Path out) { Remove-Item -Recurse -Force out }"

  build:
    desc: デバッグビルド（out/winfocus.exe）
    cmds:
      - cmd: cmd /c "scripts\\build.bat"
        platforms: [windows]
      - cmd: pwsh.exe -NoProfile -Command "Copy-Item '{{.APP_NAME}}.toml' 'out/'"
    sources:
      - src/winfocus.c
    generates:
      - out/winfocus.exe

  release:
    desc: リリースビルド + zip パッケージング
    cmds:
      - task: clean
      - task: build
      - cmd: pwsh.exe -NoProfile -Command "Compress-Archive -Path 'out/{{.APP_NAME}}.exe','out/{{.APP_NAME}}.toml' -DestinationPath 'out/{{.APP_NAME}}-v{{.VERSION}}-{{.ARCH}}.zip' -Force"
      - cmd: echo "Package out/{{.APP_NAME}}-v{{.VERSION}}-{{.ARCH}}.zip"
