# winfocus.toml
# Tray restoration whitelist

[[tray]]
process = "LINE.exe"
title = "LINE"
exe = "C:\\Users\\t_nikai\\AppData\\Local\\LINE\\bin\\current\\LINE.exe"

[[tray]]
process = "thunderbird.exe"
title = "Mozilla Thunderbird"
exe = "C:\\Users\\t_nikai\\AppData\\Local\\Microsoft\\WindowsApps\\thunderbird.exe"
